<?php

function ga_sponsor_theme($existing, $type, $theme, $path) {
  return array(
    'ga_sponsor' => array(
      'variables' => array(
        'config' => NULL,
        'sponsors' => NULL
      ),
      'template' => 'ga-sponsor'
    )
  );
}

function ga_sponsor_sponsor_update(){
  drupal_flush_all_caches();
}

function ga_sponsor_sponsor_insert(){
  drupal_flush_all_caches();
}