version: '3.1'

services:
  drupal:
    image: drupal:8.3.7-apache
    ports:
      - 8080:80
    volumes:
      - ./modules:/var/www/html/modules
      - ./themes:/var/www/html/themes

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
    volumes:
      - ./data/db:/var/lib/mysql