settings:
  library_url: 'https://cdnjs.cloudflare.com/ajax/libs/cropper/2.3.4/cropper.min.js'
  css_url: 'https://cdnjs.cloudflare.com/ajax/libs/cropper/2.3.4/cropper.min.css'
  crop_preview_image_style: crop_thumbnail
  crop_list:
    news_format: news_format
    ratio_site: ratio_site
  warn_multiple_usages: false
  show_default_crop: true
  show_crop_area: true
_core:
  default_config_hash: Nu7A-_9XQJ6mwtc1Dfm0ua3mSFoWzG-pC-xEL-SejjA
langcode: fr
