<?php
function gamers_assembly_preprocess_node(&$variables) {
  $variables['host'] = \Drupal::request()->getHost();

  if ($variables['node']->getType() == "news") {
    $variables['lastNews'] = \Drupal\ga_news\NewsUtils::getLastNews();
    $variables['nodeImage'] = \Drupal\ga_news\NewsUtils::getImageUri($variables['node'], "field_news_image");
  }
  return $variables;
}

/*function gamers_assembly_preprocess_views_view(&$variables)
{
    if ($variables['view']->id() == "news") {
    }
}*/
