<?php

function ga_front_theme($existing, $type, $theme, $path)
{
    return array(
        'ga_front_live' => array(
            'variables' => array(
                'streams' => null,
                'news' => null,
                'sponsors' => null
            ),
            'template' => 'ga-front-live'
        ),
        'ga_front_prelive' => array(
            'variables' => array(
                'config' => null,
                'slides' => null,
                'sponsors' => null,
                'news' => null
            ),
            'template' => 'ga-front-prelive'
        )
    );
}