<?php

function ga_front_theme($existing, $type, $theme, $path) {
  return array(
    'ga_front_live' => array(
      'variables' => array(
        'config' => NULL,
        'streams' => NULL,
        'news' => NULL,
        'sponsors' => NULL,
        'results' => NULL
      ),
      'template' => 'ga-front-live'
    ),
    'ga_front_prelive' => array(
      'variables' => array(
        'config' => NULL,
        'slides' => NULL,
        'sponsors' => NULL,
        'news' => NULL
      ),
      'template' => 'ga-front-prelive'
    )
  );
}