name: 'Gamers Assembly Configuration'
type: module
core: 8.x
dependencies:
  - block
  - ckeditor
  - content_translation
  - editor
  - field
  - filter
  - imce
  - language
  - node
  - system
  - taxonomy
  - text
  - user
  - views
package: 'Gamers Assembly'
