ga_game.game.*:
  type: config_entity
  label: 'Game config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: string
      label: 'Description'
    shortName:
      type: string
      label: 'Short name'
    color:
      type: string
      label: 'Color'
    editor:
      type: string
      label: 'Editor'
    type:
      type: string
      label: 'Type'
    image:
      type: image
      label: 'Image'
    uuid:
      type: string
