config_view.settings:
  path: '/admin/config/config_view'
  defaults:
    _form: '\Drupal\config_view\Form\ConfigViewForm'
    _title: 'Configuration Entity Settings'
  requirements:
    _permission: 'administer site configuration'
