<?php
	
function ga_weezevent_theme($existing, $type, $theme, $path) {
  return array(
    'ga_weezevent' => array(
      'variables' => array(
        'config' => NULL,
        'weezdata' => NULL,
      ),
      'template' => 'ga-weezevent'
    )
  );
}

function ga_weezevent_update_tournament_info_cron() {
  $config = \Drupal::config('ga_weezevent.settings');
  $weezevent = new \Drupal\ga_weezevent\WeezeventAPI($config->get('api_key'), $config->get('access_token'), $config->get('id_event'));

  $tournamentNids = \Drupal::entityQuery('node')
    ->condition('status', 1)
    ->condition('type', 'tournament')
    ->exists('field_tournament_weezevent_id')
    ->execute();

  foreach ($tournamentNids as $nid) {
    $node = \Drupal\node\Entity\Node::load($nid);
    try {
      \Drupal::logger('ga_weezevent')->info("Update tournament ".$node->getTitle()." with id ".$node->field_tournament_weezevent_id->value."\n");

      $result = $weezevent->participants($node->field_tournament_weezevent_id->value);
      $ticket_info = $weezevent->ticket_info($node->field_tournament_weezevent_id->value);

      $tickets = array();
      if (isset($result)) {
        foreach ($result->participants as $participant) {
          if ($participant->id_event > 0) { // PATCH : il arrive que le flux retour de weezevent contienne des billets sans infos (supprimes manuellement en admin du BO?)
          $team = NULL;
          $pseudo = NULL;
          foreach ($participant->answers as $answer) {
            if ($answer->label === "Nom d'équipe") {
              $team = $answer->value;
            }
            if ($answer->label === "Pseudo") {
              $pseudo = $answer->value;
            }
          }
          $key = $participant->id_transaction;
          if (isset($ticket_info->group_size)) { // cas d'un tournoi par équipe
            $newteam = $team;
            $i=2;
            while ( isset($tickets[$key]) && isset($tickets[$key][$newteam])&& (count($tickets[$key][$newteam]) == ((int)$ticket_info->group_size))) {
              $newteam = $team . $i;
              $i++;
            }
            $tickets[$key][$newteam][] = $pseudo;
          } else { // cas d'un tournoi solo
            $tickets[][$team][] = $pseudo;															
          }
        }
        }
        if (isset($ticket_info->group_size)) {
          $count = ((int) $ticket_info->participants) / ( (int) $ticket_info->group_size);
        } else {
          $count = (int) $ticket_info->participants;
        }
        $node->field_tournament_subscribers->setValue(json_encode($tickets));
        $node->field_tournament_sub_count->setValue($count);
        $node->save();
      }
    } catch (Exception $e) {
           watchdog_exception('ga_weezevent', $e);
    }
  }
}
