facebook_url: 'https://www.facebook.com/GamersAssembly'
twitter_url: 'https://twitter.com/GamersAssembly'
flickr_url: 'https://www.flickr.com/photos/futurolan'
twitch_url: 'https://twitch.tv/gamers_assembly'
youtube_url: 'https://www.youtube.com/channel/UCbfhRIAsc4xdRACnDUwRfRw'
main_sponsor_image:
  - '948'
main_sponsor_url: 'http://www.grandpoitiers.fr/'
langcode: fr
external_news_url: ''
