page_alter: false
raw_names: false
error_handlers:
  1: 1
rebuild_theme: false
debug_mail_file_format: '%to-%subject-%datetime.mail.txt'
debug_mail_directory: 'temporary://devel-mails'
devel_dumper: default
langcode: fr
_core:
  default_config_hash: 2fUHOjXYfhwa3PN3B15LZyEurQtHxNEVH7wc6tfzdYk
