edition_name: 'Edition 2017'
event_title: 'L''évènement BABA'
event_text: "<p>L'édition 2017 de la Gamer Assembly aura lieu du 26 au 28 Mars, et se déroulera au Parc des Expositions de Poitiers.</p>\r\n"
event_cta: '+ d''infos'
planning_text: "<p>Découvrez l'intégralité du programme, les conférences, les évènements de cette édition 2017 de la Gamer Assembly.</p>\r\n"
planning_cta: Programme
ticket_text: "<p>Commandez vos billets pour la Gamer Assembly 2014 dès à présent</p>\r\n"
ticket_cta: Billeterie
