edition_name: '2017 edition'
b1_title: Event
b1_text: "<p>The 2017 edition of the Gamers Assembly will take place from 15 to 17 April 2017, and will take place at the Exhibition Center in Poitiers.\r\n</p>\r\n"
b1_cta: More...
b2_title: 'An unmissable event'
b2_text: "<p>With more than 1800 players and 17 000 visits in 2016, the Gamers Assembly is the must-see for all fans of video games !\r\n</p>\r\n"
b3_title: Ticketing
b3_text: "<p>Ticketing is now open ! Players or visitors, book your seats now for the Gamers Assembly 2017! </p>\r\n"
b3_cta: Ticketing
