title: Partenaires
langcode: fr
lvl0: 'Nom de niveau 0 configurable'
lvl1: 'Nom de niveau 1 configurable'
lvl2: 'Nom de niveau 2 configurable'
lvl3: 'Nom de niveau 3 configurable'
lvl4: 'Nom de niveau 4 configurable'
