ga_front.prelive.settings:
  type: config_object
  label: 'Front prelive settings'
  mapping:
    title:
      type: text
      label: 'Title'
    edition_name:
      type: text
      label: 'Edition name'
    b1_title:
      type: text
      label: 'Box 1 title'
    b1_text:
      type: text
      label: 'Box 1 text'
    b1_cta:
      type: text
      label: 'Box 1 cta'
    b2_title:
      type: text
      label: 'Box 2 title'
    b2_text:
      type: text
      label: 'Box 2 text'
    b2_cta:
      type: text
      label: 'Box 2 cta'
    b3_title:
      type: text
      label: 'Box 3 title'
    b3_text:
      type: text
      label: 'Box 3 text'
    b3_cta:
      type: text
      label: 'Box 3 cta'