ga_ticket.settings:
  type: config_object
  label: 'Ticket settings'
  mapping:
    title:
      type: text
      label: 'Title'
    weezevent_code:
      type: text
      label: 'Weezevent Code'